POST http://localhost:4000/api/reviews
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZDJjYWJmY2YwZGMzZTRmYzNlNWYyNSIsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNzQxOTgxMTM2LCJleHAiOjE3NDE5ODQ3MzZ9.LnudJ9qYlVToC5ule15zbn_3Sf8bG054Kk7LjElFfLU
Content-Type: application/json

{
  "courseId": "67d2dd98e13b84034248f449", 
  "studentId": "67d44b1d0b02580f4e31dd16", 
  "rating": 5,
  "comment": "Great course! I learned a lot about Node.js."
}
