GET http://localhost:4000/api/courses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZDJjYWJmY2YwZGMzZTRmYzNlNWYyNSIsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNzQxOTgxMTM2LCJleHAiOjE3NDE5ODQ3MzZ9.LnudJ9qYlVToC5ule15zbn_3Sf8bG054Kk7LjElFfLU
