GET http://localhost:4000/api/courses/67d2dd98e13b84034248f449
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZDJjYWJmY2YwZGMzZTRmYzNlNWYyNSIsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNzQxOTY1MjAyLCJleHAiOjE3NDE5Njg4MDJ9.9M-Hj045sgN-1wR6waVT_KWYGiWpKcmgffiJDq26gNM
