POST http://localhost:4000/api/students/67d44b1d0b02580f4e31dd16/enroll/67d44837fbb7449ab0f58600
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZDJjYWJmY2YwZGMzZTRmYzNlNWYyNSIsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNzQxOTY1MjAyLCJleHAiOjE3NDE5Njg4MDJ9.9M-Hj045sgN-1wR6waVT_KWYGiWpKcmgffiJDq26gNM

